### ISSUE TITLE
Outbound Links Not Being Tracked as Events

### ISSUE THREAD

**Issue by grpace** [Chicago-Digital/ad-google-analytics#2]
Hey Scott, working through setting this up on https://www.michiganavenuehearinghealth.com/ and aren't able to track outbound links. This is the first site I've seen with Goals setup for Outbound links. 

![image](https://user-images.githubusercontent.com/10174859/81427095-d9a98280-911f-11ea-91cc-490c7c08877f.png)

Example buttons on: https://www.michiganavenuehearinghealth.com/visit/guide/

Can't get any of these to track in real-time event tracking to set up the goals. 

Let me know if you are able to fix this.

**Comment by scottshefler** [comment]
I just did some additional testing and it seems to be working to me. The event is triggering and I setup a goal that is triggering as well. I noticed in your image above you have the "Label" or the actual outbound link hard coded in there. Is this goal being setup for only one outbound link in particular? Because if you're setting this up for all outbound links you should leave that blank and the label will be filled in dynamically with the href.

**Comment by grpace** [comment]
Thanks Scott, I tested this on another site - I think it might have caching related. We should be good to close this out.
